/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OneTimePay } from "./OneTimePay";

export { OneTimePay__factory } from "./factories/OneTimePay__factory";
